package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmImage;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmImageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    long countByExample(FcmImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int deleteByExample(FcmImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int insert(FcmImage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int insertSelective(FcmImage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    List<FcmImage> selectByExampleWithRowbounds(FcmImageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    List<FcmImage> selectByExample(FcmImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    FcmImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmImage record, @Param("example") FcmImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmImage record, @Param("example") FcmImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FcmImage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_image
     * @mbg.generated
     */
    int updateByPrimaryKey(FcmImage record);
}