package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProductImageExample;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProductImageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmProductImageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    long countByExample(FcmProductImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int deleteByExample(FcmProductImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int deleteByPrimaryKey(FcmProductImageKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int insert(FcmProductImageKey record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int insertSelective(FcmProductImageKey record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    List<FcmProductImageKey> selectByExampleWithRowbounds(FcmProductImageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    List<FcmProductImageKey> selectByExample(FcmProductImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmProductImageKey record, @Param("example") FcmProductImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_image
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmProductImageKey record, @Param("example") FcmProductImageExample example);
}