package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProduct;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmProductMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    long countByExample(FcmProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int deleteByExample(FcmProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int insert(FcmProduct record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int insertSelective(FcmProduct record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    List<FcmProduct> selectByExampleWithRowbounds(FcmProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    List<FcmProduct> selectByExample(FcmProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    FcmProduct selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmProduct record, @Param("example") FcmProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmProduct record, @Param("example") FcmProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FcmProduct record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    int updateByPrimaryKey(FcmProduct record);
}