package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProductLang;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmProductLangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmProductLangMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    long countByExample(FcmProductLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int deleteByExample(FcmProductLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int insert(FcmProductLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int insertSelective(FcmProductLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    List<FcmProductLang> selectByExampleWithRowbounds(FcmProductLangExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    List<FcmProductLang> selectByExample(FcmProductLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    FcmProductLang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmProductLang record, @Param("example") FcmProductLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmProductLang record, @Param("example") FcmProductLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FcmProductLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    int updateByPrimaryKey(FcmProductLang record);
}