package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmSkuLang;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmSkuLangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmSkuLangMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    long countByExample(FcmSkuLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int deleteByExample(FcmSkuLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int insert(FcmSkuLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int insertSelective(FcmSkuLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    List<FcmSkuLang> selectByExampleWithRowbounds(FcmSkuLangExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    List<FcmSkuLang> selectByExample(FcmSkuLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    FcmSkuLang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmSkuLang record, @Param("example") FcmSkuLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmSkuLang record, @Param("example") FcmSkuLangExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FcmSkuLang record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    int updateByPrimaryKey(FcmSkuLang record);
}