package com.hjx.mgear.platform.fcmoto.db.dao.auto;

import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmSkuImageExample;
import com.hjx.mgear.platform.fcmoto.db.entity.auto.FcmSkuImageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FcmSkuImageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    long countByExample(FcmSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int deleteByExample(FcmSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int deleteByPrimaryKey(FcmSkuImageKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int insert(FcmSkuImageKey record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int insertSelective(FcmSkuImageKey record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    List<FcmSkuImageKey> selectByExampleWithRowbounds(FcmSkuImageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    List<FcmSkuImageKey> selectByExample(FcmSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FcmSkuImageKey record, @Param("example") FcmSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    int updateByExample(@Param("record") FcmSkuImageKey record, @Param("example") FcmSkuImageExample example);
}