package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_category
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmCategory implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_category.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_category.name
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_category.name_cn
     * @mbg.generated
     */
    private String nameCn;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_category.url
     * @mbg.generated
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_category
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_category.id
     * @return  the value of fcm_category.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    public FcmCategory withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_category.id
     * @param id  the value for fcm_category.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_category.name
     * @return  the value of fcm_category.name
     * @mbg.generated
     */
    public String getName() {

        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    public FcmCategory withName(String name) {

        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_category.name
     * @param name  the value for fcm_category.name
     * @mbg.generated
     */
    public void setName(String name) {

        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_category.name_cn
     * @return  the value of fcm_category.name_cn
     * @mbg.generated
     */
    public String getNameCn() {

        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    public FcmCategory withNameCn(String nameCn) {

        this.setNameCn(nameCn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_category.name_cn
     * @param nameCn  the value for fcm_category.name_cn
     * @mbg.generated
     */
    public void setNameCn(String nameCn) {

        this.nameCn = nameCn;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_category.url
     * @return  the value of fcm_category.url
     * @mbg.generated
     */
    public String getUrl() {

        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    public FcmCategory withUrl(String url) {

        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_category.url
     * @param url  the value for fcm_category.url
     * @mbg.generated
     */
    public void setUrl(String url) {

        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", nameCn=").append(nameCn);
        sb.append(", url=").append(url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmCategory other = (FcmCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
               && (this.getNameCn() == null ? other.getNameCn() == null : this.getNameCn().equals(other.getNameCn())) && (this.getUrl() == null ? other.getUrl() == null
                                                                                                                                                : this.getUrl().equals(other.getUrl()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_category
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNameCn() == null) ? 0 : getNameCn().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        return result;
    }
}