package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_product
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmProduct implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.product_id
     * @mbg.generated
     */
    private Integer productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.brand_id
     * @mbg.generated
     */
    private Integer brandId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.category_id
     * @mbg.generated
     */
    private Integer categoryId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.price
     * @mbg.generated
     */
    private BigDecimal price;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.price_str
     * @mbg.generated
     */
    private String priceStr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.title
     * @mbg.generated
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.detail
     * @mbg.generated
     */
    private String detail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product.url
     * @mbg.generated
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_product
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.product_id
     * @return  the value of fcm_product.product_id
     * @mbg.generated
     */
    public Integer getProductId() {

        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withProductId(Integer productId) {

        this.setProductId(productId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.product_id
     * @param productId  the value for fcm_product.product_id
     * @mbg.generated
     */
    public void setProductId(Integer productId) {

        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.brand_id
     * @return  the value of fcm_product.brand_id
     * @mbg.generated
     */
    public Integer getBrandId() {

        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withBrandId(Integer brandId) {

        this.setBrandId(brandId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.brand_id
     * @param brandId  the value for fcm_product.brand_id
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {

        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.category_id
     * @return  the value of fcm_product.category_id
     * @mbg.generated
     */
    public Integer getCategoryId() {

        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withCategoryId(Integer categoryId) {

        this.setCategoryId(categoryId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.category_id
     * @param categoryId  the value for fcm_product.category_id
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {

        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.price
     * @return  the value of fcm_product.price
     * @mbg.generated
     */
    public BigDecimal getPrice() {

        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withPrice(BigDecimal price) {

        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.price
     * @param price  the value for fcm_product.price
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {

        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.price_str
     * @return  the value of fcm_product.price_str
     * @mbg.generated
     */
    public String getPriceStr() {

        return priceStr;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withPriceStr(String priceStr) {

        this.setPriceStr(priceStr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.price_str
     * @param priceStr  the value for fcm_product.price_str
     * @mbg.generated
     */
    public void setPriceStr(String priceStr) {

        this.priceStr = priceStr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.title
     * @return  the value of fcm_product.title
     * @mbg.generated
     */
    public String getTitle() {

        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withTitle(String title) {

        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.title
     * @param title  the value for fcm_product.title
     * @mbg.generated
     */
    public void setTitle(String title) {

        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.detail
     * @return  the value of fcm_product.detail
     * @mbg.generated
     */
    public String getDetail() {

        return detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withDetail(String detail) {

        this.setDetail(detail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.detail
     * @param detail  the value for fcm_product.detail
     * @mbg.generated
     */
    public void setDetail(String detail) {

        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product.url
     * @return  the value of fcm_product.url
     * @mbg.generated
     */
    public String getUrl() {

        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    public FcmProduct withUrl(String url) {

        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product.url
     * @param url  the value for fcm_product.url
     * @mbg.generated
     */
    public void setUrl(String url) {

        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", brandId=").append(brandId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", price=").append(price);
        sb.append(", priceStr=").append(priceStr);
        sb.append(", title=").append(title);
        sb.append(", detail=").append(detail);
        sb.append(", url=").append(url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmProduct other = (FcmProduct) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId())) && (this.getBrandId() == null ? other.getBrandId() == null
                                                                                                                                                             : this.getBrandId().equals(other
                                                                                                                                                                                             .getBrandId()))
               && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId())) && (this.getPrice() == null ? other.getPrice() == null
                                                                                                                                                                  : this.getPrice().equals(other
                                                                                                                                                                                                .getPrice()))
               && (this.getPriceStr() == null ? other.getPriceStr() == null : this.getPriceStr().equals(other.getPriceStr())) && (this.getTitle() == null ? other.getTitle() == null
                                                                                                                                                          : this.getTitle().equals(other.getTitle()))
               && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail())) && (this.getUrl() == null ? other.getUrl() == null
                                                                                                                                                : this.getUrl().equals(other.getUrl()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPriceStr() == null) ? 0 : getPriceStr().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        return result;
    }
}