package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_product_lang
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmProductLang implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product_lang.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product_lang.product_id
     * @mbg.generated
     */
    private Integer productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product_lang.language_id
     * @mbg.generated
     */
    private Integer languageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product_lang.title
     * @mbg.generated
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_product_lang.detail
     * @mbg.generated
     */
    private String detail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product_lang.id
     * @return  the value of fcm_product_lang.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    public FcmProductLang withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product_lang.id
     * @param id  the value for fcm_product_lang.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product_lang.product_id
     * @return  the value of fcm_product_lang.product_id
     * @mbg.generated
     */
    public Integer getProductId() {

        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    public FcmProductLang withProductId(Integer productId) {

        this.setProductId(productId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product_lang.product_id
     * @param productId  the value for fcm_product_lang.product_id
     * @mbg.generated
     */
    public void setProductId(Integer productId) {

        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product_lang.language_id
     * @return  the value of fcm_product_lang.language_id
     * @mbg.generated
     */
    public Integer getLanguageId() {

        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    public FcmProductLang withLanguageId(Integer languageId) {

        this.setLanguageId(languageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product_lang.language_id
     * @param languageId  the value for fcm_product_lang.language_id
     * @mbg.generated
     */
    public void setLanguageId(Integer languageId) {

        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product_lang.title
     * @return  the value of fcm_product_lang.title
     * @mbg.generated
     */
    public String getTitle() {

        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    public FcmProductLang withTitle(String title) {

        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product_lang.title
     * @param title  the value for fcm_product_lang.title
     * @mbg.generated
     */
    public void setTitle(String title) {

        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_product_lang.detail
     * @return  the value of fcm_product_lang.detail
     * @mbg.generated
     */
    public String getDetail() {

        return detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    public FcmProductLang withDetail(String detail) {

        this.setDetail(detail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_product_lang.detail
     * @param detail  the value for fcm_product_lang.detail
     * @mbg.generated
     */
    public void setDetail(String detail) {

        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", languageId=").append(languageId);
        sb.append(", title=").append(title);
        sb.append(", detail=").append(detail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmProductLang other = (FcmProductLang) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getProductId() == null ? other.getProductId() == null
                                                                                                                                   : this.getProductId().equals(other.getProductId())) && (this
                                                                                                                                                                                               .getLanguageId() == null ? other.getLanguageId() == null
                                                                                                                                                                                                                        : this.getLanguageId()
                                                                                                                                                                                                                              .equals(other.getLanguageId()))
               && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle())) && (this.getDetail() == null ? other.getDetail() == null
                                                                                                                                               : this.getDetail().equals(other.getDetail()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_product_lang
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getLanguageId() == null) ? 0 : getLanguageId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        return result;
    }
}