package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_sku_image
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmSkuImageKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_image.sku_id
     * @mbg.generated
     */
    private Integer skuId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_image.image_id
     * @mbg.generated
     */
    private Integer imageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_image.sku_id
     * @return  the value of fcm_sku_image.sku_id
     * @mbg.generated
     */
    public Integer getSkuId() {

        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    public FcmSkuImageKey withSkuId(Integer skuId) {

        this.setSkuId(skuId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_image.sku_id
     * @param skuId  the value for fcm_sku_image.sku_id
     * @mbg.generated
     */
    public void setSkuId(Integer skuId) {

        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_image.image_id
     * @return  the value of fcm_sku_image.image_id
     * @mbg.generated
     */
    public Integer getImageId() {

        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    public FcmSkuImageKey withImageId(Integer imageId) {

        this.setImageId(imageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_image.image_id
     * @param imageId  the value for fcm_sku_image.image_id
     * @mbg.generated
     */
    public void setImageId(Integer imageId) {

        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", skuId=").append(skuId);
        sb.append(", imageId=").append(imageId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmSkuImageKey other = (FcmSkuImageKey) that;
        return (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId())) && (this.getImageId() == null ? other.getImageId() == null
                                                                                                                                             : this.getImageId().equals(other.getImageId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_image
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getImageId() == null) ? 0 : getImageId().hashCode());
        return result;
    }
}