package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_sku
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmSku implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.sku_id
     * @mbg.generated
     */
    private Integer skuId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.product_id
     * @mbg.generated
     */
    private Integer productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.stock
     * @mbg.generated
     */
    private Integer stock;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.available
     * @mbg.generated
     */
    private Boolean available;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.variation_json
     * @mbg.generated
     */
    private String variationJson;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.attribute_values
     * @mbg.generated
     */
    private String attributeValues;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku.url
     * @mbg.generated
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_sku
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.sku_id
     * @return  the value of fcm_sku.sku_id
     * @mbg.generated
     */
    public Integer getSkuId() {

        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withSkuId(Integer skuId) {

        this.setSkuId(skuId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.sku_id
     * @param skuId  the value for fcm_sku.sku_id
     * @mbg.generated
     */
    public void setSkuId(Integer skuId) {

        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.product_id
     * @return  the value of fcm_sku.product_id
     * @mbg.generated
     */
    public Integer getProductId() {

        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withProductId(Integer productId) {

        this.setProductId(productId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.product_id
     * @param productId  the value for fcm_sku.product_id
     * @mbg.generated
     */
    public void setProductId(Integer productId) {

        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.stock
     * @return  the value of fcm_sku.stock
     * @mbg.generated
     */
    public Integer getStock() {

        return stock;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withStock(Integer stock) {

        this.setStock(stock);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.stock
     * @param stock  the value for fcm_sku.stock
     * @mbg.generated
     */
    public void setStock(Integer stock) {

        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.available
     * @return  the value of fcm_sku.available
     * @mbg.generated
     */
    public Boolean getAvailable() {

        return available;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withAvailable(Boolean available) {

        this.setAvailable(available);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.available
     * @param available  the value for fcm_sku.available
     * @mbg.generated
     */
    public void setAvailable(Boolean available) {

        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.variation_json
     * @return  the value of fcm_sku.variation_json
     * @mbg.generated
     */
    public String getVariationJson() {

        return variationJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withVariationJson(String variationJson) {

        this.setVariationJson(variationJson);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.variation_json
     * @param variationJson  the value for fcm_sku.variation_json
     * @mbg.generated
     */
    public void setVariationJson(String variationJson) {

        this.variationJson = variationJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.attribute_values
     * @return  the value of fcm_sku.attribute_values
     * @mbg.generated
     */
    public String getAttributeValues() {

        return attributeValues;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withAttributeValues(String attributeValues) {

        this.setAttributeValues(attributeValues);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.attribute_values
     * @param attributeValues  the value for fcm_sku.attribute_values
     * @mbg.generated
     */
    public void setAttributeValues(String attributeValues) {

        this.attributeValues = attributeValues;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku.url
     * @return  the value of fcm_sku.url
     * @mbg.generated
     */
    public String getUrl() {

        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    public FcmSku withUrl(String url) {

        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku.url
     * @param url  the value for fcm_sku.url
     * @mbg.generated
     */
    public void setUrl(String url) {

        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", skuId=").append(skuId);
        sb.append(", productId=").append(productId);
        sb.append(", stock=").append(stock);
        sb.append(", available=").append(available);
        sb.append(", variationJson=").append(variationJson);
        sb.append(", attributeValues=").append(attributeValues);
        sb.append(", url=").append(url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmSku other = (FcmSku) that;
        return (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId())) && (this.getProductId() == null ? other.getProductId() == null
                                                                                                                                               : this.getProductId().equals(other.getProductId()))
               && (this.getStock() == null ? other.getStock() == null : this.getStock().equals(other.getStock())) && (this.getAvailable() == null ? other.getAvailable() == null
                                                                                                                                                  : this.getAvailable().equals(other.getAvailable()))
               && (this.getVariationJson() == null ? other.getVariationJson() == null : this.getVariationJson().equals(other.getVariationJson())) && (this.getAttributeValues() == null ? other
                                                                                                                                                                                               .getAttributeValues() == null
                                                                                                                                                                                        : this.getAttributeValues()
                                                                                                                                                                                              .equals(other.getAttributeValues()))
               && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getStock() == null) ? 0 : getStock().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        result = prime * result + ((getVariationJson() == null) ? 0 : getVariationJson().hashCode());
        result = prime * result + ((getAttributeValues() == null) ? 0 : getAttributeValues().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        return result;
    }
}