package com.hjx.mgear.platform.fcmoto.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fcm_sku_lang
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FcmSkuLang implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_lang.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_lang.sku_id
     * @mbg.generated
     */
    private Integer skuId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_lang.language_id
     * @mbg.generated
     */
    private Integer languageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column fcm_sku_lang.variation_json
     * @mbg.generated
     */
    private String variationJson;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_lang.id
     * @return  the value of fcm_sku_lang.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    public FcmSkuLang withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_lang.id
     * @param id  the value for fcm_sku_lang.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_lang.sku_id
     * @return  the value of fcm_sku_lang.sku_id
     * @mbg.generated
     */
    public Integer getSkuId() {

        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    public FcmSkuLang withSkuId(Integer skuId) {

        this.setSkuId(skuId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_lang.sku_id
     * @param skuId  the value for fcm_sku_lang.sku_id
     * @mbg.generated
     */
    public void setSkuId(Integer skuId) {

        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_lang.language_id
     * @return  the value of fcm_sku_lang.language_id
     * @mbg.generated
     */
    public Integer getLanguageId() {

        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    public FcmSkuLang withLanguageId(Integer languageId) {

        this.setLanguageId(languageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_lang.language_id
     * @param languageId  the value for fcm_sku_lang.language_id
     * @mbg.generated
     */
    public void setLanguageId(Integer languageId) {

        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column fcm_sku_lang.variation_json
     * @return  the value of fcm_sku_lang.variation_json
     * @mbg.generated
     */
    public String getVariationJson() {

        return variationJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    public FcmSkuLang withVariationJson(String variationJson) {

        this.setVariationJson(variationJson);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column fcm_sku_lang.variation_json
     * @param variationJson  the value for fcm_sku_lang.variation_json
     * @mbg.generated
     */
    public void setVariationJson(String variationJson) {

        this.variationJson = variationJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", skuId=").append(skuId);
        sb.append(", languageId=").append(languageId);
        sb.append(", variationJson=").append(variationJson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcmSkuLang other = (FcmSkuLang) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
               && (this.getLanguageId() == null ? other.getLanguageId() == null : this.getLanguageId().equals(other.getLanguageId())) && (this.getVariationJson() == null ? other
                                                                                                                                                                                 .getVariationJson() == null
                                                                                                                                                                          : this.getVariationJson()
                                                                                                                                                                                .equals(other.getVariationJson()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fcm_sku_lang
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getLanguageId() == null) ? 0 : getLanguageId().hashCode());
        result = prime * result + ((getVariationJson() == null) ? 0 : getVariationJson().hashCode());
        return result;
    }
}