package com.hjx.mgear.common.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table brand_lang
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BrandLang implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand_lang.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand_lang.brand_id
     * @mbg.generated
     */
    private Integer brandId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand_lang.language_id
     * @mbg.generated
     */
    private Integer languageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand_lang.name
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand_lang.detail
     * @mbg.generated
     */
    private String detail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table brand_lang
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand_lang.id
     * @return  the value of brand_lang.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    public BrandLang withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand_lang.id
     * @param id  the value for brand_lang.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand_lang.brand_id
     * @return  the value of brand_lang.brand_id
     * @mbg.generated
     */
    public Integer getBrandId() {

        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    public BrandLang withBrandId(Integer brandId) {

        this.setBrandId(brandId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand_lang.brand_id
     * @param brandId  the value for brand_lang.brand_id
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {

        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand_lang.language_id
     * @return  the value of brand_lang.language_id
     * @mbg.generated
     */
    public Integer getLanguageId() {

        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    public BrandLang withLanguageId(Integer languageId) {

        this.setLanguageId(languageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand_lang.language_id
     * @param languageId  the value for brand_lang.language_id
     * @mbg.generated
     */
    public void setLanguageId(Integer languageId) {

        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand_lang.name
     * @return  the value of brand_lang.name
     * @mbg.generated
     */
    public String getName() {

        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    public BrandLang withName(String name) {

        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand_lang.name
     * @param name  the value for brand_lang.name
     * @mbg.generated
     */
    public void setName(String name) {

        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand_lang.detail
     * @return  the value of brand_lang.detail
     * @mbg.generated
     */
    public String getDetail() {

        return detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    public BrandLang withDetail(String detail) {

        this.setDetail(detail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand_lang.detail
     * @param detail  the value for brand_lang.detail
     * @mbg.generated
     */
    public void setDetail(String detail) {

        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brandId=").append(brandId);
        sb.append(", languageId=").append(languageId);
        sb.append(", name=").append(name);
        sb.append(", detail=").append(detail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrandLang other = (BrandLang) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getBrandId() == null ? other.getBrandId() == null
                                                                                                                                 : this.getBrandId().equals(other.getBrandId())) && (this
                                                                                                                                                                                         .getLanguageId() == null ? other.getLanguageId() == null
                                                                                                                                                                                                                  : this.getLanguageId()
                                                                                                                                                                                                                        .equals(other.getLanguageId()))
               && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName())) && (this.getDetail() == null ? other.getDetail() == null
                                                                                                                                           : this.getDetail().equals(other.getDetail()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand_lang
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getLanguageId() == null) ? 0 : getLanguageId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        return result;
    }
}