package com.hjx.mgear.common.db.entity.auto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table brand
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Brand implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column brand.code
     * @mbg.generated
     */
    private String code;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table brand
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand.id
     * @return  the value of brand.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    public Brand withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand.id
     * @param id  the value for brand.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column brand.code
     * @return  the value of brand.code
     * @mbg.generated
     */
    public String getCode() {

        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    public Brand withCode(String code) {

        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column brand.code
     * @param code  the value for brand.code
     * @mbg.generated
     */
    public void setCode(String code) {

        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Brand other = (Brand) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        return result;
    }
}