package com.hjx.mgear.common.db.entity.auto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table language
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Language implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column language.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column language.code
     * @mbg.generated
     */
    private String code;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column language.name
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column language.last_modified
     * @mbg.generated
     */
    private Date lastModified;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table language
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column language.id
     * @return  the value of language.id
     * @mbg.generated
     */
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    public Language withId(Integer id) {

        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column language.id
     * @param id  the value for language.id
     * @mbg.generated
     */
    public void setId(Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column language.code
     * @return  the value of language.code
     * @mbg.generated
     */
    public String getCode() {

        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    public Language withCode(String code) {

        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column language.code
     * @param code  the value for language.code
     * @mbg.generated
     */
    public void setCode(String code) {

        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column language.name
     * @return  the value of language.name
     * @mbg.generated
     */
    public String getName() {

        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    public Language withName(String name) {

        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column language.name
     * @param name  the value for language.name
     * @mbg.generated
     */
    public void setName(String name) {

        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column language.last_modified
     * @return  the value of language.last_modified
     * @mbg.generated
     */
    public Date getLastModified() {

        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    public Language withLastModified(Date lastModified) {

        this.setLastModified(lastModified);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column language.last_modified
     * @param lastModified  the value for language.last_modified
     * @mbg.generated
     */
    public void setLastModified(Date lastModified) {

        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", lastModified=").append(lastModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {

        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Language other = (Language) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
               && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName())) && (this.getLastModified() == null ? other.getLastModified() == null
                                                                                                                                                 : this.getLastModified().equals(other
                                                                                                                                                                                      .getLastModified()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLastModified() == null) ? 0 : getLastModified().hashCode());
        return result;
    }
}