package com.hjx.mgear.common.db.dao.auto;

import com.hjx.mgear.common.db.entity.auto.Brand;
import com.hjx.mgear.common.db.entity.auto.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BrandMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    long countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    List<Brand> selectByExampleWithRowbounds(BrandExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    Brand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table brand
     * @mbg.generated
     */
    int updateByPrimaryKey(Brand record);
}