package com.hjx.mgear.common.db.dao.auto;

import com.hjx.mgear.common.db.entity.auto.Language;
import com.hjx.mgear.common.db.entity.auto.LanguageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LanguageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    long countByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int deleteByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int insertSelective(Language record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    List<Language> selectByExampleWithRowbounds(LanguageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    List<Language> selectByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    Language selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int updateByExample(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Language record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table language
     * @mbg.generated
     */
    int updateByPrimaryKey(Language record);
}